networks:
  kafka_network:

volumes:
  Kafka00:
    driver: local
  Kafka01:
    driver: local
  Kafka02:
    driver: local

services:
  Kafka00Service:
    image: confluentinc/cp-kafka:latest
    restart: unless-stopped # 컨테이너 수동 중지하지 않은 경우 종료되면 재시작
    container_name: Kafka00Container
    ports:
      - '13530:9094' # 외부 포트:내부 포트
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_NODE_ID: 0
      KAFKA_CLUSTER_ID: 019a1fc9-fd09-74c0-be72-9a815ccc7bb1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@Kafka00Service:9093,1@Kafka01Service:9093,2@Kafka02Service:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://Kafka00Service:9092,EXTERNAL://127.0.0.1:13530
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_CONTROLLER_HEARTBEAT_INTERVAL_MS: 3000
      KAFKA_CONTROLLER_SESSION_TIMEOUT_MS: 18000
      KAFKA_CONTROLLER_ELECTION_TIMEOUT_MS: 5000
    networks:
      - kafka_network
    volumes:
      # 메인 데이터 디렉토리
      - ./kafka-data/Kafka00:/var/lib/kafka/data
      # 로그 디렉토리
      - ./kafka-data/Kafka00:/logs/var/log/kafka
      # 설정 디렉토리 (선택사항)
      - ./kafka-data/Kafka00:/config/etc/kafka
  
  Kafka01Service:
    image: confluentinc/cp-kafka:latest
    restart: unless-stopped # 컨테이너 수동 중지하지 않은 경우 종료되면 재시작
    container_name: Kafka01Container
    ports:
      - '13531:9094' # 외부 포트:내부 포트
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_CLUSTER_ID: 019a1fc9-fd09-74c0-be72-9a815ccc7bb1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@Kafka00Service:9093,1@Kafka01Service:9093,2@Kafka02Service:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://Kafka01Service:9092,EXTERNAL://127.0.0.1:13531
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_CONTROLLER_HEARTBEAT_INTERVAL_MS: 3000
      KAFKA_CONTROLLER_SESSION_TIMEOUT_MS: 18000
      KAFKA_CONTROLLER_ELECTION_TIMEOUT_MS: 5000
    networks:
      - kafka_network
    volumes:
      # 메인 데이터 디렉토리
      - ./kafka-data/Kafka01:/var/lib/kafka/data
      # 로그 디렉토리
      - ./kafka-data/Kafka01:/logs/var/log/kafka
      # 설정 디렉토리 (선택사항)
      - ./kafka-data/Kafka01:/config/etc/kafka
  
  Kafka02Service:
    image: confluentinc/cp-kafka:latest
    restart: unless-stopped # 컨테이너 수동 중지하지 않은 경우 종료되면 재시작
    container_name: Kafka02Container
    ports:
      - '13532:9094' # 외부 포트:내부 포트
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_NODE_ID: 2
      KAFKA_CLUSTER_ID: 019a1fc9-fd09-74c0-be72-9a815ccc7bb1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@Kafka00Service:9093,1@Kafka01Service:9093,2@Kafka02Service:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://Kafka02Service:9092,EXTERNAL://127.0.0.1:13532
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_CONTROLLER_HEARTBEAT_INTERVAL_MS: 3000
      KAFKA_CONTROLLER_SESSION_TIMEOUT_MS: 18000
      KAFKA_CONTROLLER_ELECTION_TIMEOUT_MS: 5000
    networks:
      - kafka_network
    volumes:
      # 메인 데이터 디렉토리
      - ./kafka-data/Kafka02:/var/lib/kafka/data
      # 로그 디렉토리
      - ./kafka-data/Kafka02:/logs/var/log/kafka
      # 설정 디렉토리 (선택사항)
      - ./kafka-data/Kafka02:/config/etc/kafka
  
  KafkaWebUiService:
    image: provectuslabs/kafka-ui:latest
    restart: always
    container_name: KafkaWebUiContainer
    ports:
      - '9206:8080' # 외부 포트:내부 포트
    environment:
      KAFKA_CLUSTERS_0_NAME: Local-Kafka-Cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: Kafka00Service:9092,Kafka01Service:9092,Kafka02Service:9092
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED: true
      KAFKA_CLUSTERS_0_AUDIT_CONSOLEAUDITENABLED: true
    depends_on:
      - Kafka00Service
      - Kafka01Service
      - Kafka02Service
    networks:
      - kafka_network